core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    path("", include("accounts.urls", namespace="accounts")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path 
from .views import ProjectIndex,ProjectListView,ProjectNearDueListView,ProjectDetailView,KanbanView,update_task,ProjectUpdateView,ProjectDeleteView

app_name = 'projects'

urlpatterns = [
    path('index/',ProjectIndex.as_view(),name='pro_index'),
    path('list/',ProjectListView.as_view(),name='pro_list'),
    path('list/due/',ProjectNearDueListView.as_view(),name='pro_due_list'),
    path('detail/<uuid:pk>/',ProjectDetailView.as_view(),name='project_detail'),
    path('edit/<uuid:pk>/',ProjectUpdateView.as_view(),name='project_update'),
    path('delete/<uuid:pk>/',ProjectDeleteView.as_view(),name='project_delete'),
    path('kanban/<uuid:pk>/',KanbanView.as_view(),name='kanban_dashboard'),
    path('update/<uuid:pk>/',update_task,name='update_task'),
    
]

projects/forms.py
from django import forms

from teams.models import Team
from .models import Project,AttachMentFile


class ProjectFormCreation(forms.ModelForm):
    team = forms.ModelChoiceField(
        queryset=Team.objects.only("name"),
        empty_label="Choose Team To Work With",
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
        required=True,
    )
    status = forms.ChoiceField(
        choices=[("", "-------------")] + list(Project.STATUS_CHOICE),
        widget=forms.Select(attrs={"class": "form-select mb-3"}),
        label="Choose Status",
        required=True,
    )
    priority = forms.ChoiceField(
        choices=[("", "-------------")] + list(Project.PRIORITY_CHOICE),
        widget=forms.Select(attrs={"class": "form-select mb-3"}),
        label="Choose Priority",
        required=True,
    )
    name = forms.CharField(
        label="Project Name",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "project name"}
        ),
        required=True,
    )
    client_company = forms.CharField(
        label="Client Company",
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "client company  / site",
            }
        ),
        required=True,
    )
    description = forms.CharField(
        label="Project description",
        widget=forms.Textarea(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "project description",
                "rows": 4,
            }
        ),
        required=True,
    )
    active = forms.CharField(
        label=" Active To Work ",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input p-2 mb-3 me-1"}),
    )
    start_date = forms.DateField(
        label="Start Date",
        widget=forms.DateInput(
            attrs={"type": "date", "class": "form-control mb-3"}
        ),
        required=True,
    )
    due_date = forms.DateField(
        label="Due Date",
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control mb-3"}),
        required=True,
    )

    class Meta:
        model = Project
        fields = (
            "team",
            "name",
            "client_company",
            "description",
            "status",
            "priority",
            "active",
            "start_date",
            "due_date",
            "total_amount",
            "amount_spent",
            "estimated_duration",
        )

    def clean_total_amount(self):
        if self.cleaned_data.get("total_amount") < 0:
            raise forms.ValidationError("it should greater then zero")
        return self.cleaned_data["total_amount"]

    def clean_amount_spent(self):
        if self.cleaned_data.get("amount_spent") < 0:
            raise forms.ValidationError("it should greater then zero")
        return self.cleaned_data["amount_spent"]

    def clean_estimated_duration(self):
        if self.cleaned_data.get("estimated_duration") < 0:
            raise forms.ValidationError("it should greater then zero")
        return self.cleaned_data["estimated_duration"]


class AttachForm(forms.ModelForm):
    name = forms.CharField(label='Prefix Name ',required=True)
    class Meta:
        model = AttachMentFile
        fields = ['name','file_upload']

projects/views.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView,DeleteView

from notifications.task import create_notification, create_task_notification
from projects.forms import ProjectFormCreation, AttachForm
from projects.models import Project
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from comments.forms import CommentForm
from tasks.forms import TaskFormCreationModel
from tasks.models import Task

from django.utils import timezone
from django.http import Http404
from django.db.models import Q


class ProjectIndex(CreateView):
    model = Project
    form_class = ProjectFormCreation
    success_url = reverse_lazy("accounts:dashboard")
    template_name = "projects/index.html"

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            obj = form.save(commit=False)
            obj.owner = self.request.user
            obj.save()

            # send notification
            actor = self.request.user.username
            verb = f"Project {obj.name} was Assigned"
            obj_id = obj.id

            create_notification.delay(actor_name=actor, verb=verb, object_id=obj_id)
            return redirect(self.success_url)
        else:
            messages.error(self.request, "user has no permission to create")
            return redirect(self.request.path_info)


class ProjectListView(ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = "projects"
    paginate_by = 6
    
    def get_queryset(self):
      user = self.request.user 
      projects = Project.objects.filter( Q(owner=user) | Q(team__member=user) ).distinct() 
      return projects
    


class ProjectNearDueListView(ListView):
    def get_queryset(self):
        user = self.request.user 
        projects_near = Project.objects.due_t_or_less().filter( Q(owner=user) | Q(team__member=user) ).distinct() 
        return projects_near

    model = Project
    template_name = "projects/project_near_list.html"
    context_object_name = "projects"
    paginate_by = 6


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    context_object_name = "project"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.get_object()
        comments = Comment.objects.filter_by_instance_model(project)
        context["comments"] = comments
        paginator = Paginator(comments, 3)

        page_number = self.request.GET.get("page")
        try:
            page_obj = paginator.page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        context["page_obj"] = page_obj
        context["form_comment"] = CommentForm()
        context["form_attach"] = AttachForm()
        return context

    def post(self, request, *args, **kwargs):
        project = self.get_object()
        if request.user not in project.team.member.all():
            messages.error(request, "You do not have access on this project.")
            return redirect("projects:project_detail", pk=project.id)

        form = CommentForm(request.POST)
        if "comment_submit" in request.POST:
            if form.is_valid():
                form_comment = form.save(commit=False)
                form_comment.user = request.user
                form_comment.content_object = project
                form_comment.save()

                # send notification
                actor = self.request.user.username
                verb = f"Comment on {project.name} Writing By {actor}"
                obj_id = project.id

                create_notification.delay(actor_name=actor, verb=verb, object_id=obj_id)
                messages.success(request, "Comment posted successfully!")
            else:
                for field, errors in form.errors.items():
                    messages.error(request, f"{errors[0]}")

        if "attach_submit" in request.POST:
            form = AttachForm(request.POST, request.FILES)
            if form.is_valid():
                attach = form.save(commit=False)
                attach.project = project
                attach.user = request.user
                attach.save()
                # send notification
                actor = self.request.user.username
                verb = f"File was Uploaded on this {project.name}  By {actor}"
                obj_id = project.id
                create_notification.delay(actor_name=actor, verb=verb, object_id=obj_id)
                messages.success(request, "Upload file successfully!")
                return redirect("projects:project_detail", pk=project.id)
            else:
                for field, errors in form.errors.items():
                    messages.error(request, f"{errors[0]}")

        return redirect("projects:project_detail", pk=project.id)


class KanbanView(DetailView):
    model = Project
    template_name = "projects/kanban.html"
    context_object_name = "project"

    def get_context_data(self, **kwargs):
        project = self.get_object()
        context = super().get_context_data(**kwargs)
        context["task_backlog"] = project.tasks.filter(status="Backlog").upComing()
        context["task_to_do"] = project.tasks.filter(status="To Do").upComing()
        context["task_progress"] = project.tasks.filter(status="In Progress").upComing()
        context["task_completed"] = project.tasks.filter(status="Completed").upComing()
        context["form"] = TaskFormCreationModel()
        return context

    def post(self, request, *args, **kwargs):
        project = self.get_object()
        if request.user not in project.team.member.all():
            messages.error(
                request, "You do not have access to Create Task on this project."
            )
            return redirect("projects:project_detail", pk=project.id)

        form = TaskFormCreationModel(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.owner = request.user
            task.team = project.team
            task.start_date = timezone.now()
            task.save()
            # send notification
            actor = request.user.username
            verb = f"Task {task.name} was Assigned"
            obj_id = task.id

            create_task_notification.delay(
                actor_name=actor, verb=verb, object_id=obj_id
            )
            messages.success(request, "Task Created!")
            return redirect("projects:kanban_dashboard", pk=project.id)
        else:
            for field, errors in form.errors.items():
                messages.error(request, f"{errors[0]}")

        return redirect("projects:kanban_dashboard", pk=project.id)


def update_task(request, pk):
    task = get_object_or_404(Task, id=pk)
    if request.method == "POST":
        if request.user not in task.team.member.all():
            messages.error(request, "You do not have an access on this project.")
            return redirect("projects:project_detail", pk=task.project.id)

        if task.owner == request.user.username:
            messages.error(
                request, "You do not have an access on this project. you do not owner"
            )
            return redirect("projects:project_detail", pk=task.project.id)

        form = TaskFormCreationModel(request.POST, instance=task)
        if form.is_valid():
            form.save()
            # send notification
            actor = request.user.username
            verb = f"Task {task.name} was Updated"
            obj_id = task.id

            create_task_notification.delay(
                actor_name=actor, verb=verb, object_id=obj_id
            )
            messages.success(request, "Task Updated!")
            return redirect("projects:kanban_dashboard", pk=task.project.id)
    else:
        form = TaskFormCreationModel(instance=task)
    context = {"form": form, "task": task}
    return render(request, "tasks/update_task.html", context)


class ProjectUpdateView(UpdateView):
    model = Project
    template_name = "projects/project_update.html"
    context_object_name = "project"
    form_class = ProjectFormCreation

    def get_object(self):
        project = get_object_or_404(Project, pk=self.kwargs["pk"])
        if project.owner != self.request.user:
            raise Http404("not access")
        return project

    def form_invalid(self, form):
        messages.error(self.request, "please correct the error")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Updated Success")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("projects:project_detail", kwargs={'pk':self.object.pk})
    
    
class ProjectDeleteView(DeleteView):
    model = Project
    template_name = "projects/project_delete.html"
    context_object_name = "project"


    def get_object(self):
        project = get_object_or_404(Project, pk=self.kwargs["pk"])
        if project.owner != self.request.user:
            raise Http404("not access")
        return project

    def form_invalid(self, form):
        messages.error(self.request, "please correct the error")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Deleted Success")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("projects:pro_list")

templates/projects/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
project/create
{% endblock %}

{% block dash_link %} <a href="">Project</a>{% endblock dash_link %}
{% block dash_active %}Create Project{% endblock dash_active %} 


{% block main_content %}
<form action="" method="post">
  <div class="row g-1 g-md-2 g-lg-5">
      {% csrf_token %}
      <div class="col-md-6 me-3 bg-white rounded rounded-3 p-3 mb-5 me-1">
        <div class="card-header">
          <h5 class="">Create Project</h5>
          <hr />
        </div>
        <div class="mb-3">{{ form.team|as_crispy_field }}</div>
        <div class="mb-3">{{ form.name|as_crispy_field }}</div>
        <div class="mb-3">{{ form.client_company|as_crispy_field }}</div>
        <div class="mb-3">{{ form.description|as_crispy_field }}</div>
        <div class="mb-3">{{ form.status|as_crispy_field }}</div>
        <div class="mb-3">{{ form.priority|as_crispy_field }}</div>
        <div class="mb-3">{{ form.active|as_crispy_field }}</div>
        <div class="mb-3">{{ form.start_date|as_crispy_field }}</div>
        <div class="mb-3">{{ form.due_date|as_crispy_field }}</div>
        <button type="submit" class="btn btn-outline-dark px-4 my-4 ms-auto">Create Project</button>
      </div>
      <div class="col-md-5 bg-white rounded rounded-3 p-3 mb-5" style="height: 450px !important;">
        <div class="card-header">
          <h5>Budget</h5>
          <hr />
        </div>
        <div class="mb-3">{{ form.total_amount|as_crispy_field }}</div>
        <div class="mb-3">{{ form.amount_spent|as_crispy_field }}</div>
        <div class="mb-3">{{ form.estimated_duration|as_crispy_field }}</div>
      </div>
    </div>
</form>
{% endblock %}

templates/projects/project_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
project/delete
{% endblock %}

{% block dash_link %} <a href="">Project</a>{% endblock dash_link %}
{% block dash_active %}Delete Project{% endblock dash_active %} 


{% block main_content %}
<form action="" method="post">
  <div class="row g-1 g-md-2 g-lg-5">
      {% csrf_token %}
      <div class="col-md-6 me-3 bg-white rounded rounded-3 p-3 mb-5 me-1">
        <div class="card-header">
          <h5 class="">Delete Project</h5>
          <hr />

          Would You Like to Delete This - <b class="text-danger">{{project.name|title}}</b> - project
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-dark px-4 my-4">Delete Project</button>
            <a href="{% url "projects:pro_due_list" %}" class="btn btn-outline-dark px-4 my-4 ">Cancel</a>
        </div>
    
      </div>
    </div>
</form>
{% endblock %}

templates/projects/project_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  project/list
{% endblock %}

{% block dash_link %}
  <a href="">Project</a>
{% endblock %}
{% block dash_active %}
  All Projects
{% endblock %}

{% block main_content %}
<a href="{% url "projects:pro_index" %}" class="btn btn-dark px-4 my-3">Create Project <i class="feather feather-plus"></i></a>
  <div class="card stretch stretch-full">
    <div class="card-body p-0">
      <div class="table-responsive">
        <div id="projectList_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
          <div class="row dt-row">
            <div class="col-sm-12">
              <table class="table table-hover dataTable no-footer" id="projectList" aria-describedby="projectList_info">
                <thead>
                  <tr>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">#</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Project Name</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Customer/Company</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Team Work</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Start Date</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">End Date</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Priority</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Status</th>
                    <th rowspan="1" colspan="2" class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for project in projects %}
                    <tr class="single-item odd">
                      <td>{{ forloop.counter }}</td>
                      <td>{{ project.name|title }}</td>

                      <td>
                        <a href="projects-view.html" class="text-truncate-1-line">{{ project.client_company }}</a>
                      </td>

                      <td>
                        <div class="d-flex">
                          {% for pro in project.team.member.all %}
                            <span class="avatar-image avatar-md me-1"><img src="{{ pro.profile.get_profile_image }}" alt="" class="img-fluid" /></span>
                          {% endfor %}
                        </div>
                      </td>

                      <td>{{ project.start_date }}</td>
                      <td>{{ project.due_date }}</td>
                      <td class="text-{{ project.get_priority_color }}" style="font-style: italic;">{{ project.priority }}</td>
                      <td class="text-{{ project.get_status_color }}" style="font-style: italic;">
                        <small>{{ project.status }}</small>
                        <div class="progress mt-2 ht-5">
                          <div class="progress-bar bg-{{ project.get_status_color }}" role="progressbar" style="width: {{ project.progress }}%"></div>
                        </div>
                      </td>
                      <td>
                        <div class="hstack gap-2 justify-content-end">
                          {% if request.user == project.owner %}
                          <a href="{{ project.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          <a href="{% url "projects:project_update" project.pk %}" class="avatar-text avatar-md"><i class="feather feather-edit"></i></a>
                          <a href="{% url "projects:project_delete" project.pk  %}" class="avatar-text avatar-md"><i class="feather feather-trash-2"></i></a>
                          {% else %}
                          <a href="{{ project.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          {% endif %}
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12 col-md-5">
              <div class="dataTables_info" id="projectList_info" role="status" aria-live="polite">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} entries</div>
            </div>
            <div class="col-sm-12 col-md-7">
              <div class="dataTables_paginate paging_simple_numbers" id="projectList_paginate">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous mx-1" id="projectList_previous">
                      <a href="?page={{ page_obj.previous_page_number }}" aria-controls="projectList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item previous disabled mx-1" id="projectList_previous">
                      <a href="#" aria-controls="projectList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% endif %}
                  <li class="paginate_button page-item active mx-1">
                    <a href="#" aria-controls="projectList" data-dt-idx="0" tabindex="0" class="page-link">{{ page_obj.number }}</a>
                  </li>

                  <li class="paginate_button page-item mx-1">
                    <a class="page-link">{{ page_obj.paginator.num_pages }}</a>
                  </li>
                  {% if page_obj.has_next %}
                    <li class="paginate_button page-item next mx-1" id="projectList_next">
                      <a href="?page={{ page_obj.next_page_number }}" aria-controls="projectList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item next disabled mx-1" id="projectList_next">
                      <a href="#" aria-controls="projectList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/projects/project_near_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  project/list
{% endblock %}

{% block dash_link %}
  <a href="">Project</a>
{% endblock %}
{% block dash_active %}
  All Projects Near Due
{% endblock %}

{% block main_content %}
<a href="{% url "projects:pro_index" %}" class="btn btn-dark px-4 my-3">Create Project <i class="feather feather-plus"></i></a>

  <div class="card stretch stretch-full">
    <div class="card-body p-0">
      <div class="table-responsive">
        <div id="projectList_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
          <div class="row dt-row">
            <div class="col-sm-12">
              <table class="table table-hover dataTable no-footer" id="projectList" aria-describedby="projectList_info">
                <thead>
                  <tr>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">#</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Project Name</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Customer/Company</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Team Work</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Start Date</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">End Date</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Priority</th>
                    <th tabindex="0" aria-controls="projectList" rowspan="1" colspan="1">Status</th>
                    <th rowspan="1" colspan="2" class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for project in projects %}
                    <tr class="single-item odd">
                      <td>{{ forloop.counter }}</td>
                      <td>{{ project.name|title }}</td>

                      <td>
                        <a href="projects-view.html" class="text-truncate-1-line">{{ project.client_company }}</a>
                      </td>

                      <td>
                        <div class="d-flex">
                          {% for pro in project.team.member.all %}
                            <span class="avatar-image avatar-md me-1"><img src="{{ pro.profile.get_profile_image }}" alt="" class="img-fluid" /></span>
                          {% endfor %}
                        </div>
                      </td>

                      <td>{{ project.start_date }}</td>
                      <td>{{ project.due_date }}</td>
                      <td class="text-{{ project.get_priority_color }}" style="font-style: italic;">{{ project.priority }}</td>
                      <td class="text-{{ project.get_status_color }}" style="font-style: italic;">
                        <small>{{ project.status }}</small>
                        <div class="progress mt-2 ht-5">
                          <div class="progress-bar bg-{{ project.get_status_color }}" role="progressbar" style="width: {{ project.progress }}%"></div>
                        </div>
                      </td>
                      <td>
                        <div class="hstack gap-2 justify-content-end">
                          {% if request.user == project.owner %}
                          <a href="{{ project.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          <a href="" class="avatar-text avatar-md"><i class="feather feather-edit"></i></a>
                          <a href="{% url "projects:project_delete" project.pk  %}" class="avatar-text avatar-md"><i class="feather feather-trash-2"></i></a>
                          {% else %}
                          <a href="{{ project.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          {% endif %}
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-5">
              <div class="dataTables_info" id="projectList_info" role="status" aria-live="polite">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} entries</div>
            </div>
            <div class="col-sm-12 col-md-7">
              <div class="dataTables_paginate paging_simple_numbers" id="projectList_paginate">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous mx-1" id="projectList_previous">
                      <a href="?page={{ page_obj.previous_page_number }}" aria-controls="projectList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item previous disabled mx-1" id="projectList_previous">
                      <a href="#" aria-controls="projectList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% endif %}
                  <li class="paginate_button page-item active mx-1">
                    <a href="#" aria-controls="projectList" data-dt-idx="0" tabindex="0" class="page-link">{{ page_obj.number }}</a>
                  </li>

                  <li class="paginate_button page-item mx-1">
                    <a class="page-link">{{ page_obj.paginator.num_pages }}</a>
                  </li>
                  {% if page_obj.has_next %}
                    <li class="paginate_button page-item next mx-1" id="projectList_next">
                      <a href="?page={{ page_obj.next_page_number }}" aria-controls="projectList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item next disabled mx-1" id="projectList_next">
                      <a href="#" aria-controls="projectList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}