accounts/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from .views import (
    ProfileList,
    DashboardView,
    account_login,
    account_logout,
    UserDetailView,
    email_activated,
    register,
    UserEditView
)

app_name = "accounts"


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("register/", register, name="register"),
    path("activate/<uidb64>/<token>/", email_activated, name="activate"),
    path("login/", account_login, name="login"),
    path("profile/list/", ProfileList.as_view(), name="profile_list"),
    path("profile/detail/<int:pk>/", UserDetailView.as_view(), name="profile_user"),
    path("profile/edit/<int:pk>/", UserEditView.as_view(), name="profile_edit"),
    path("logout/", account_logout, name="logout"),
    # reset password
    path(
        "reset-password/",
        PasswordResetView.as_view(
            template_name="accounts/reset/pws_reset.html",
            email_template_name="accounts/reset/pws_reset_email.html",
            success_url=reverse_lazy("accounts:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "reset-password-done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/reset/pws_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/reset/pws_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/reset/pws_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    path("", include("accounts.urls", namespace="accounts")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.db.models.signals import post_save, pre_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
import os
from django.utils.timesince import timesince
from django.utils import timezone
import shutil
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra):
        if not email:
            raise ValueError("The Email field must be set")

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, **extra):
        extra.setdefault("is_active", True)
        extra.setdefault("is_staff", True)
        extra.setdefault("is_superuser", True)

        return self.create_user(email, username, password, **extra)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email"), max_length=255, unique=True, db_index=True)
    username = models.CharField(_("username"), max_length=60, unique=True)
    is_active = models.BooleanField(_("active"), default=False)
    is_staff = models.BooleanField(_("staff"), default=False)
    is_superuser = models.BooleanField(_("superuser"), default=False)

    join_at = models.DateTimeField(_("join at"), auto_now_add=True)
    last_login = models.DateTimeField(_("last login"), auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username


def profile_image_location(instance, fileName):
    date_upload = timezone.now().strftime("%Y-%m-%d")
    return f"profile/{instance.user.username}/{ date_upload}/ {fileName}"


class Profile(models.Model):
    user = models.OneToOneField(
        User, verbose_name=_("user"), on_delete=models.CASCADE, related_name="profile"
    )
    job_title = models.CharField(_("job title"), max_length=150, null=True, blank=True)
    photo = models.ImageField(_("photo"), upload_to=profile_image_location)
    phone = PhoneNumberField(_("phone"), null=True, blank=True, unique=True)
    address = models.CharField(_("address"), max_length=255, null=True, blank=True)
    update_at = models.DateTimeField(_("update"), auto_now=True)
    bio = models.CharField(_("bio"), max_length=255, null=True, blank=True)
    location = models.CharField(_("location"), max_length=255, null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def get_profile_image(self):
        try:
            image = self.photo.url
        except:
            image = os.path.join("media/default_user.jpg")
        return image

    @property
    def get_date_joined(self):
        time_difference = timezone.now() - self.user.join_at
        if time_difference <= timezone.timedelta(days=2):
            return timesince(self.user.join_at) + " ago"
        else:
            return self.user.join_at.strftime("%d %b")
        
        
    def get_absolute_url(self):
        return reverse("accounts:profile_user", kwargs={"pk": self.pk})
        


# Signals
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, **kwargs):
    # if there a user it will updated . else it created one
    Profile.objects.get_or_create(user=instance)


# this signal for update profile with delete old
@receiver(pre_save, sender=Profile)
def delete_old_file_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).photo
    except sender.DoesNotExist:
        return False

    new_file = instance.photo
    if old_file:
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)


# this for delete also image if he was deleted
@receiver(post_delete, sender=Profile)
def delete_file_on_delete(sender, instance, **kwargs):
    if instance.photo:
        # if i remove just a path of photo
        # if os.path.isfile(instance.photo.path):
        #     os.remove(instance.photo.path)

        # this for delete folder that has folder  hold photo path like /username/2026-01-30
        folder_path = os.path.dirname(os.path.dirname(instance.photo.path))
        # Deletes the folder and the image
        if os.path.exists(folder_path):
            shutil.rmtree(folder_path)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile
User = get_user_model()


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput({"placeholder": "Enter your email","class":"form-control mb-3"}))
    username = forms.CharField(widget=forms.TextInput({"placeholder": "Choose a username","class":"form-control mb-3"}))
    password1 = forms.CharField(label="Enter Password",widget=forms.PasswordInput({"placeholder": "Enter Password","class":"form-control mb-3"}))
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput({"placeholder": "Confirm Password","class":"form-control mb-3"}))
    
    
    class Meta:
        model = User
        fields = ("email", "username") 
        
class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), required=True)
    class Meta:
        model = Profile
        fields = ( 'job_title', 'photo', 'phone', 'address', 'bio', 'location')     

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth import authenticate, login, logout
from accounts.models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_not_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import ProfileForm, RegisterUserForm
from .tokens import account_activation_token
from django.shortcuts import render
from django.views.generic import View

from projects.models import Project
from tasks.models import Task
from teams.models import Team
from django.db.models import Q
from django.http import Http404
from django.core.exceptions import PermissionDenied


@login_not_required
def account_login(request):
    email = request.POST.get("email")
    password = request.POST.get("password")
    user = authenticate(request, email=email, password=password)
    remember_me = request.POST.get("remember_me")
    if user is not None:
        if remember_me:
            request.session.set_expiry(1209600)
        else:
            request.session.set_expiry(0)
        login(request, user)
        return redirect("accounts:dashboard")
    return render(request, "accounts/registrations/login.html")


def account_logout(request):
    logout(request)
    messages.success(request, "Logged Out")
    return redirect("accounts:dashboard")


User = get_user_model()


@login_not_required
def send_user_email(request, user):
    current_site = get_current_site(request).domain
    protocol = "http"
    subject = "Activate your account"

    context = {
        "user": user,
        "protocol": protocol,
        "domain": current_site,
        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
        "token": account_activation_token.make_token(user),
    }

    body = render_to_string("accounts/registrations/email_.html", context)

    email = EmailMessage(subject, body, "admin@site.com", [user.email])
    email.send(fail_silently=False)


@login_not_required
def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            send_user_email(request, user)
            messages.success(
                request, "Please check your email to activate your account."
            )
            return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid input")
    else:
        form = RegisterUserForm()
    return render(request, "accounts/registrations/register.html", {"form": form})


@login_not_required
def email_activated(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Your account has been activated!")
        return redirect("accounts:dashboard")
    else:
        messages.error(request, "The activation link is invalid or has expired.")
    return redirect("accounts:dashboard")


class ProfileList(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "accounts/profile/profile_list.html"
    context_object_name = "profiles"
    paginate_by = 6


class DashboardView(View):
    def get(self, request):
        if request.user.is_superuser:
            projects_le = Project.objects.due_t_or_less()[:5]
            projects_counts = Project.objects.all()
            tasks = Task.objects.due_t_or_less()[:5]
            tasks_count = Task.objects.all().active().count()
            task_in_progress = Task.objects.all().filter(status="In Progress").count()
            task_completed = Task.objects.all().filter(status="Completed").count()
            profiles = Profile.objects.all()[:4]
            projects = Project.objects.all().active().count()
            project_in_progress = (
                Project.objects.all().filter(status="In Progress").count()
            )
            projects_completed = (
                Project.objects.all().filter(status="Completed").count()
            )

            if tasks_count > 0:
                task_percentage = (task_completed / tasks_count) * 100
            else:
                task_percentage = 0

            if projects > 0:
                project_percentage = (projects_completed / projects) * 100
            else:
                project_percentage = 0

            teams = Team.objects.all().count()

            if teams > 0:
                team_percentage = (projects_completed / teams) * 100
            else:
                team_percentage = 0
        else:
            projects_le = Project.objects.due_t_or_less().filter(owner=request.user)[:5]
            projects_counts = Project.objects.filter(owner=request.user)
            tasks = Task.objects.due_t_or_less().filter(owner=request.user)[:5]
            tasks_count = Task.objects.filter(owner=request.user).active().count()
            task_in_progress = Task.objects.filter(
                status="In Progress", owner=request.user
            ).count()
            task_completed = Task.objects.filter(
                status="Completed", owner=request.user
            ).count()
            profiles = Profile.objects.get(user=request.user)
            projects = Project.objects.filter(owner=request.user).active().count()
            project_in_progress = Project.objects.filter(
                Q(status="In Progress") and Q(owner=request.user)
            ).count()
            projects_completed = Project.objects.filter(
                Q(status="Completed") and Q(owner=request.user)
            ).count()

            if tasks_count > 0:
                task_percentage = (task_completed / tasks_count) * 100
            else:
                task_percentage = 0

            if projects > 0:
                project_percentage = (projects_completed / projects) * 100
            else:
                project_percentage = 0

            teams = Team.objects.all().count()

            if teams > 0:
                team_percentage = (projects_completed / teams) * 100
            else:
                team_percentage = 0

        context = {
            "projects": projects_le,
            "projects_counts": projects_counts,
            "tasks": tasks,
            "profiles": profiles,
            "project_in_progress": project_in_progress,
            "projects_completed": projects_completed,
            "project_percentage": project_percentage,
            "task_in_progress": task_in_progress,
            "tasks_count": tasks_count,
            "task_percentage": task_percentage,
            "task_completed": task_completed,
            "teams": teams,
            "team_percentage": team_percentage,
        }

        return render(request, "accounts/dashboard.html", context)


class UserDetailView(DetailView):
    model = Profile
    template_name = "accounts/profile/user_detail.html"
    context_object_name = "profile"


class UserEditView(UpdateView):
    model = Profile
    template_name = "accounts/profile/user_edit.html"
    context_object_name = "profile"
    form_class = ProfileForm

    def get_object(self, queryset=None):
        if not self.request.user.is_superuser:
            raise PermissionDenied("You cannot access this profile.")
        
        return super().get_object(queryset)

    def form_valid(self, form):
        messages.success(self.request, "Updated Successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Invalid Input. Please check the fields.")
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("accounts:profile_list")

templates/accounts/reset/pws_reset.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  reset link
{% endblock %}
{% block auth_content %}
  <div class="card my-4 overflow-hidden" style="z-index: 1">
    <div class="row flex-1 g-0">
      <div class="col-lg-6 h-100 my-auto order-1 order-lg-0">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible shadow fade show p-3 mx-auto mt-2" role="alert" style="width: 80%;">
              {{ message|safe }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        <div class="wd-50 bg-white p-2 rounded-circle shadow-lg position-absolute translate-middle top-50 start-50 d-none d-lg-block">
          <img src="{% static 'assets/images/logo-abbr.png' %} " alt="" class="img-fluid" />
        </div>
        <div class="creative-card-body card-body p-sm-5">
          <h2 class="fs-20 fw-bolder mb-4">Reset</h2>
          <h4 class="fs-13 fw-bold mb-2">Reset to your username/password</h4>
          <p class="fs-12 fw-medium text-muted">Enter your email and a reset link will sent to you, let's access our the best recommendation for you.</p>
          <form action="" class="w-100 mt-4 pt-2" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <div class="mt-5">
              <button type="submit" class="btn btn-lg btn-primary w-100">Reset Now</button>
            </div>
          </form>
          <div class="mt-5 text-muted">
            <span>Don't have an account?</span>
            <a href="{% url "accounts:register" %}" class="fw-bold">Create an Account</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 bg-primary order-0 order-lg-1">
        <div class="h-100 d-flex align-items-center justify-content-center">
          <img src="{% static 'assets/images/auth/auth-user.png' %} " alt="" class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/reset/pws_reset_complete.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}
  reset complete
{% endblock %}
{% block auth_content %}
  <div class="card my-4 overflow-hidden" style="z-index: 1">
    <div class="row flex-1 g-0">
      <div class="col-lg-6 h-100 my-auto order-1 order-lg-0">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible shadow fade show p-3 mx-auto mt-2" role="alert" style="width: 80%;">
              {{ message|safe }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        <div class="wd-50 bg-white p-2 rounded-circle shadow-lg position-absolute translate-middle top-50 start-50 d-none d-lg-block">
          <img src="{% static 'assets/images/logo-abbr.png' %} " alt="" class="img-fluid" />
        </div>
        <div class="creative-card-body card-body p-sm-5">
          <h2 class="fs-20 fw-bolder mb-4">Reset</h2>
          <h4 class="fs-16 fw-bold mb-2">Reset complete</h4>
          <p class="fs-14 fw-medium text-muted">Success Completed Reset </p>
          
          <div class="mt-5 text-muted">

            <a href="{% url "accounts:login" %}" class="fw-bold btn btn-primary">Go to Login now </a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 bg-primary order-0 order-lg-1">
        <div class="h-100 d-flex align-items-center justify-content-center">
          <img src="{% static 'assets/images/auth/auth-user.png' %} " alt="" class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/reset/pws_reset_confirm.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Reset
{% endblock %}
{% block auth_content %}
  <div class="card my-4 overflow-hidden" style="z-index: 1">
    <div class="row flex-1 g-0">
      <div class="col-lg-6 h-100 my-auto order-1 order-lg-0">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible shadow fade show p-3 mx-auto mt-2" role="alert" style="width: 80%;">
              {{ message|safe }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        <div class="wd-50 bg-white p-2 rounded-circle shadow-lg position-absolute translate-middle top-50 start-50 d-none d-lg-block">
          <img src="{% static 'assets/images/logo-abbr.png' %} " alt="" class="img-fluid" />
        </div>
        <div class="creative-card-body card-body p-sm-5">
          <h2 class="fs-20 fw-bolder mb-4">Resetting</h2>
          <h4 class="fs-13 fw-bold mb-2">Reset to your password</h4>
          <p class="fs-12 fw-medium text-muted">Enter your email and a reset link will sent to you, let's access our the best recommendation for you.</p>
          <form action="" class="w-100 mt-4 pt-2" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <div class="mt-5">
              <button type="submit" class="btn btn-lg btn-primary w-100">Save Change</button>
            </div>
          </form>
          <div class="mt-5 text-muted">
            <span>Don't have an account?</span>
            <a href="auth-register-creative.html" class="fw-bold">Create an Account</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 bg-primary order-0 order-lg-1">
        <div class="h-100 d-flex align-items-center justify-content-center">
          <img src="{% static 'assets/images/auth/auth-user.png' %} " alt="" class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/reset/pws_reset_done.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}
  reset done
{% endblock %}
{% block auth_content %}
  <div class="card my-4 overflow-hidden" style="z-index: 1">
    <div class="row flex-1 g-0">
      <div class="col-lg-6 h-100 my-auto order-1 order-lg-0">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible shadow fade show p-3 mx-auto mt-2" role="alert" style="width: 80%;">
              {{ message|safe }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        <div class="wd-50 bg-white p-2 rounded-circle shadow-lg position-absolute translate-middle top-50 start-50 d-none d-lg-block">
          <img src="{% static 'assets/images/logo-abbr.png' %} " alt="" class="img-fluid" />
        </div>
        <div class="creative-card-body card-body p-sm-5">
          <h4 class="fs-16 fw-bold mb-2">Reset Done</h4>
          <p class="fs-14 fw-medium text-muted">Please Check Your E_mail </p>
          
        </div>
      </div>
      <div class="col-lg-6 bg-primary order-0 order-lg-1">
        <div class="h-100 d-flex align-items-center justify-content-center">
          <img src="{% static 'assets/images/auth/auth-user.png' %} " alt="" class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/reset/pws_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}