core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    path("", include("accounts.urls", namespace="accounts")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import (
    TaskCreateIndex,
    TaskListView,
    TaskNearDueListView,
    TaskDetailView,
    update_task_ajax,
    TaskDeleteView,
    TaskEditView,
)

app_name = "tasks"

urlpatterns = [
    path("create/", TaskCreateIndex.as_view(), name="task_create"),
    path("list/", TaskListView.as_view(), name="task_list"),
    path("list/due/", TaskNearDueListView.as_view(), name="task_due_list"),
    path("detail/<uuid:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("edit/<uuid:pk>/", TaskEditView.as_view(), name="task_edit"),
    path("delete/<uuid:pk>/", TaskDeleteView.as_view(), name="task_delete"),
    path("update_task_ajax/<uuid:task_id>/", update_task_ajax, name="update_task_ajax"),
]

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
import uuid
from django.utils import timezone
from django.urls import reverse
from teams.models import Team

User = get_user_model()


class TaskQuery(models.QuerySet):
    def active(self):
        return self.filter(active=True)

    def upComing(self):
        return self.filter(due_date__gte=timezone.now())
    
    def due_in_tow_days_or_less(self):
        today = timezone.now().date()
        tow_todays = today + timezone.timedelta(days=2)
        return self.active().upComing().filter(due_date__lte=tow_todays)
    



class TaskManager(models.Manager):
    def get_queryset(self):
        return TaskQuery(self.model, using=self._db)

    def all_upcoming(self):
        return self.get_queryset().active().upComing()
    
    def due_t_or_less(self):
        return self.get_queryset().due_in_tow_days_or_less()
    



class Task(models.Model):
    STATUS_CHOICE = (
        ("Backlog", "Backlog"),
        ("To Do", "To Do"),
        ("In Progress", "In Progress"),
        ("Completed", "Completed"),
    )
    PRIORITY_CHOICE = (
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        User, verbose_name=_("owner"), on_delete=models.CASCADE, related_name="tasks"
    )
    team = models.ForeignKey(
        Team, verbose_name=_("team"), on_delete=models.CASCADE, related_name="tasks"
    )
    project = models.ForeignKey(
        Project,
        verbose_name=_("project"),
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    name = models.CharField(_("name"), max_length=255)
    description = models.TextField(_("description"), null=True, blank=True)
    status = models.CharField(
        _("status"), max_length=20, choices=STATUS_CHOICE, default="Backlog"
    )
    priority = models.CharField(
        _("priority"), max_length=20, choices=PRIORITY_CHOICE, default="Low"
    )
    active = models.BooleanField(_("active"), default=False)
    start_date = models.DateField(_("start date"))
    due_date = models.DateField(_("due date"))
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    update_at = models.DateTimeField(_("update at"), auto_now=True)
    objects = TaskManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at",)

    def get_due_date(self):
        if self.due_date:
            current_date = timezone.now().date()
            return (self.due_date - current_date).days
        else:
            return None

    def get_priority_color(self):
        if self.priority == "Low":
            color = "success"
        elif self.priority == "Medium":
            color = "warning"
        else:
            color = "danger"
        return color
    
    def get_progress_color(self):
        if self.status == "To Do":
            color = "muted"
        elif self.status == "In Progress":
            color = "primary"
        else:
            color = "success"
        return color

    @property
    def progress(self):
        progress_dict = {
            "To Do": 0,
            "In Progress": 50,
            "Completed": 100,
        }
        return progress_dict.get(self.status, 0)
    
    def get_absolute_url(self):
        return reverse("tasks:task_detail", kwargs={"pk": self.pk})
    

tasks/forms.py
from django import forms

from teams.models import Team
from .models import Project, Task


class TaskFormCreation(forms.ModelForm):
    team = forms.ModelChoiceField(
        queryset=Team.objects.only("name"),
        empty_label="Choose Team To Work With",
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
        required=True,
    )
    project = forms.ModelChoiceField(
        queryset=Project.objects.only("name"),
        empty_label="Choose Project To Work With",
        widget=forms.Select(attrs={"class": "form-control mb-3"}),
        required=True,
    )
    status = forms.ChoiceField(
        choices=[("", "-------------")] + list(Task.STATUS_CHOICE),
        widget=forms.Select(attrs={"class": "form-select mb-3"}),
        label="Choose Status",
        required=True,
    )
    priority = forms.ChoiceField(
        choices=[("", "-------------")] + list(Task.PRIORITY_CHOICE),
        widget=forms.Select(attrs={"class": "form-select mb-3"}),
        label="Choose Priority",
        required=True,
    )
    name = forms.CharField(
        label="Task Name",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "Task name"}
        ),
        required=True,
    )

    description = forms.CharField(
        label="Task description",
        widget=forms.Textarea(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Task description",
                "rows": 4,
            }
        ),
        required=True,
    )
    active = forms.CharField(
        label=" Active To Work ",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input p-2 mb-3 me-1"}),
    )
    start_date = forms.DateField(
        label="Start Date",
        widget=forms.DateInput(
            attrs={"type": "date", "class": "form-control mb-3"}
        ),
        required=True,
    )
    due_date = forms.DateField(
        label="Due Date",
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control mb-3"}),
        required=True,
    )

    class Meta:
        model = Task
        fields = (
            "project",
            "team",
            "name",
            "description",
            "status",
            "priority",
            "active",
            "start_date",
            "due_date",
        )


class TaskFormCreationModel(forms.ModelForm):

    due_date = forms.DateField(
        label="Due Date",
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control mb-3"}),
        required=True,
    )
    description = forms.CharField(
            label="Task description",
            widget=forms.Textarea(
                attrs={
                    "class": "form-control mb-3",
                    "placeholder": "Task description",
                    "rows": 3,
                }
            ),
            required=True,
            )
    name = forms.CharField(
        label="Task Name",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "Task name"}
        ),
        required=True,
    )

        
    
    class Meta:
        model = Task
        fields = (
            "name",
            "description",
            "priority",
            "due_date",
        )

    

tasks/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)

from comments.forms import CommentForm
from comments.models import Comment
from notifications.task import create_task_notification
from projects.models import Project
from .models import Task
from .forms import TaskFormCreation
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST
import json
from django.db.models import Q
from django.http import Http404


class TaskCreateIndex(CreateView):
    model = Task
    form_class = TaskFormCreation
    success_url = reverse_lazy("accounts:dashboard")
    template_name = "tasks/create.html"

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            obj = form.save(commit=False)
            obj.owner = self.request.user
            obj.save()

            # send notification
            actor = self.request.user.username
            verb = f"Task {obj.name} was Assigned"
            obj_id = obj.id

            create_task_notification.delay(
                actor_name=actor, verb=verb, object_id=obj_id
            )
            return redirect(self.success_url)
        else:
            messages.error(self.request, "user has no permission to create")
            return redirect(self.request.path_info)


class TaskListView(ListView):
    model = Task
    template_name = "tasks/tasks_list.html"
    context_object_name = "tasks"
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        tasks = Task.objects.filter(Q(owner=user) | Q(team__member=user)).distinct()
        return tasks


class TaskNearDueListView(ListView):
    def get_queryset(self):
        user = self.request.user
        tasks_near = (
            Task.objects.due_t_or_less()
            .filter(Q(owner=user) | Q(team__member=user))
            .distinct()
        )
        return tasks_near

    model = Task
    template_name = "tasks/tasks_near_list.html"
    context_object_name = "tasks"
    paginate_by = 6


class TaskDetailView(DetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    context_object_name = "task"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        comments = Comment.objects.filter_by_instance_model(task)
        context["comments"] = comments
        paginator = Paginator(comments, 3)

        page_number = self.request.GET.get("page")
        try:
            page_obj = paginator.page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        context["page_obj"] = page_obj
        context["form_comment"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        if request.user not in task.team.member.all():
            messages.error(request, "You do not have access to comment on this task.")
            return redirect("tasks:task_detail", pk=task.id)

        form = CommentForm(request.POST)
        if form.is_valid():
            form_comment = form.save(commit=False)
            form_comment.user = request.user
            form_comment.content_object = task
            form_comment.save()

            # send notification
            actor = self.request.user.username
            verb = f"Comment on {task.name} Writing By {actor}"
            obj_id = task.id

            create_task_notification.delay(
                actor_name=actor, verb=verb, object_id=obj_id
            )
            messages.success(request, "Comment posted successfully!")
        else:
            for field, errors in form.errors.items():
                messages.error(request, f"{errors[0]}")

        return redirect("tasks:task_detail", pk=task.id)


@require_POST
def update_task_ajax(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.user not in task.team.member.all():
        return JsonResponse(
            {
                "success": False,
                "redirect_url": reverse(
                    "projects:kanban_dashboard", args=[task.project.id]
                ),
                "error": "You do not have permission to update this task.",
            }
        )

    data = json.loads(request.body)
    new_status = data.get("status").title()

    if new_status in ["Backlog", "To Do", "In Progress", "Completed"]:
        task.status = new_status
        task.save()
        return JsonResponse(
            {
                "success": True,
                "message": "Updated Success",
                "redirect_url": reverse(
                    "projects:kanban_dashboard", args=[task.project.id]
                ),
            }
        )
    else:
        return JsonResponse(
            {
                "success": False,
                "error": "Invalid Status",
                "redirect_url": reverse(
                    "projects:kanban_dashboard", args=[task.project.id]
                ),
            },
            status=400,
        )


class TaskDeleteView(DeleteView):
    model = Task
    template_name = "tasks/task_delete.html"
    context_object_name = "task"

    def get_object(self, queryset=None):
        task = get_object_or_404(Task, pk=self.kwargs["pk"])
        if task.owner != self.request.user:
            raise Http404("Not Access")
        return task

    def form_invalid(self, form):
        messages.error(self.request, "Invalid Input")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Deleted Success")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("tasks:task_list")


class TaskEditView(UpdateView):
    model = Task
    template_name = "tasks/task_edit.html"
    context_object_name = "task"
    form_class = TaskFormCreation

    def get_object(self, queryset=None):
        task = get_object_or_404(Task, pk=self.kwargs["pk"])
        if task.owner != self.request.user:
            raise Http404("Not Access")
        return task

    def form_invalid(self, form):
        messages.error(self.request, "Invalid Input")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Updated Success")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("tasks:task_list")

templates/tasks/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Task/create
{% endblock %}

{% block dash_link %}
  <a href="">Task</a>
{% endblock %}
{% block dash_active %}
  Create Task
{% endblock %}

{% block main_content %}
  <form action="" method="post">
    <div class="row g-1 g-md-2 g-lg-5">
      {% csrf_token %}
      <div class="col-md-6 me-3 bg-white rounded rounded-3 p-3 mb-5 me-1">
        <div class="card-header">
          <h5 class="">Create Task</h5>
          <hr />
        </div>
        <div class="mb-3">{{ form.project|as_crispy_field }}</div>
        <div class="mb-3">{{ form.team|as_crispy_field }}</div>
        <div class="mb-3">{{ form.name|as_crispy_field }}</div>
        <div class="mb-3">{{ form.description|as_crispy_field }}</div>
      </div>
      <div class="col-md-5 bg-white rounded rounded-3 p-3 mb-5" >
        <div class="mb-3">{{ form.status|as_crispy_field }}</div>
        <div class="mb-3">{{ form.priority|as_crispy_field }}</div>
        <div class="mb-3">{{ form.active|as_crispy_field }}</div>
        <div class="mb-3">{{ form.start_date|as_crispy_field }}</div>
        <div class="mb-3">{{ form.due_date|as_crispy_field }}</div>
        <button type="submit" class="btn btn-outline-dark px-4 my-4 ms-auto">Create Task</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/tasks/task_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
task/delete
{% endblock %}

{% block dash_link %} <a href="">Task</a>{% endblock dash_link %}
{% block dash_active %}Delete Task{% endblock dash_active %} 


{% block main_content %}
<form action="" method="post">
  <div class="row g-1 g-md-2 g-lg-5">
      {% csrf_token %}
      <div class="col-md-6 me-3 bg-white rounded rounded-3 p-3 mb-5 me-1">
        <div class="card-header">
          <h5 class="">Delete Task</h5>
          <hr />

          Would You Like to Delete This - <b class="text-danger">{{task.name|title}}</b> - Task
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-dark px-4 my-4">Delete Task</button>
            <a href="{% url "tasks:task_list" %}" class="btn btn-outline-dark px-4 my-4 ">Cancel</a>
        </div>
    
      </div>
    </div>
</form>
{% endblock %}

templates/tasks/task_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
task/edit
{% endblock %}

{% block dash_link %} <a href="">Task</a>{% endblock dash_link %}


{% block dash_active %}
  Edit Task
{% endblock %}

{% block main_content %}
  <form action="" method="post">
    <div class="row g-1 g-md-2 g-lg-5">
      {% csrf_token %}
      <div class="col-md-6 me-3 bg-white rounded rounded-3 p-3 mb-5 me-1">
        <div class="card-header">
          <h5 class="">Edit Task</h5>
          <hr />
        </div>
        <div class="mb-3">{{ form.project|as_crispy_field }}</div>
        <div class="mb-3">{{ form.team|as_crispy_field }}</div>
        <div class="mb-3">{{ form.name|as_crispy_field }}</div>
        <div class="mb-3">{{ form.description|as_crispy_field }}</div>
      </div>
      <div class="col-md-5 bg-white rounded rounded-3 p-3 mb-5" >
        <div class="mb-3">{{ form.status|as_crispy_field }}</div>
        <div class="mb-3">{{ form.priority|as_crispy_field }}</div>
        <div class="mb-3">{{ form.active|as_crispy_field }}</div>
        <div class="mb-3">{{ form.start_date|as_crispy_field }}</div>
        <div class="mb-3">{{ form.due_date|as_crispy_field }}</div>
        <button type="submit" class="btn btn-outline-dark px-4 my-4 ms-auto">Edit Task</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/tasks/tasks_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  task/list
{% endblock %}

{% block dash_link %}
  <a href="">Task</a>
{% endblock %}
{% block dash_active %}
  All Tasks
{% endblock %}

{% block main_content %}
<a href="{% url "tasks:task_create" %}" class="btn btn-dark px-4 my-3">Create Task <i class="feather feather-plus"></i></a>

  <div class="card stretch stretch-full">
    <div class="card-body p-0">
      <div class="table-responsive">
        <div id="taskList_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
          <div class="row dt-row">
            <div class="col-sm-12">
              <table class="table table-hover dataTable no-footer" id="taskList" aria-describedby="taskList_info">
                <thead>
                  <tr>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">#</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">task Name</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Team Work</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Start Date</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">End Date</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Priority</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Status</th>
                    <th rowspan="1" colspan="2" class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for task in tasks %}
                    <tr class="single-item odd">
                      <td>{{ forloop.counter }}</td>
                      <td>{{ task.name|title }}</td>
                      <td>
                        <div class="d-flex">
                          {% for pro in task.team.member.all %}
                            <span class="avatar-image avatar-md me-1"><img src="{{ pro.profile.get_profile_image }}" alt="" class="img-fluid" /></span>
                          {% endfor %}
                        </div>
                      </td>

                      <td>{{ task.start_date }}</td>
                      <td>{{ task.due_date }}</td>
                      <td class="text-{{ task.get_priority_color }}" style="font-style: italic;">{{ task.priority }}</td>
                      <td class="text-{{ task.get_status_color }}" style="font-style: italic;">
                        <small>{{ task.status }}</small>
                        <div class="progress mt-2 ht-5">
                          <div class="progress-bar bg-{{ task.get_progress_color }}" role="progressbar" style="width: {{ task.progress }}%"></div>
                        </div>
                      </td>
                      <td>
                        <div class="hstack gap-2 justify-content-end">
                          {% if request.user == task.owner %}
                          <a href="{{ task.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          <a href="{% url "tasks:task_edit" task.pk %}" class="avatar-text avatar-md"><i class="feather feather-edit"></i></a>
                          <a href="{% url "tasks:task_delete" task.pk %}" class="avatar-text avatar-md"><i class="feather feather-trash-2"></i></a>
                          {% else %}
                          <a href="{{ task.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          {% endif %}
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-5">
              <div class="dataTables_info" id="taskList_info" role="status" aria-live="polite">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} entries</div>
            </div>
            <div class="col-sm-12 col-md-7">
              <div class="dataTables_paginate paging_simple_numbers" id="taskList_paginate">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous mx-1" id="taskList_previous">
                      <a href="?page={{ page_obj.previous_page_number }}" aria-controls="taskList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item previous disabled mx-1" id="taskList_previous">
                      <a href="#" aria-controls="taskList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% endif %}
                  <li class="paginate_button page-item active mx-1">
                    <a href="#" aria-controls="taskList" data-dt-idx="0" tabindex="0" class="page-link">{{ page_obj.number }}</a>
                  </li>

                  <li class="paginate_button page-item mx-1">
                    <a class="page-link">{{ page_obj.paginator.num_pages }}</a>
                  </li>
                  {% if page_obj.has_next %}
                    <li class="paginate_button page-item next mx-1" id="taskList_next">
                      <a href="?page={{ page_obj.next_page_number }}" aria-controls="taskList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item next disabled mx-1" id="taskList_next">
                      <a href="#" aria-controls="taskList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/tasks_near_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  task/list
{% endblock %}

{% block dash_link %}
  <a href="">task</a>
{% endblock %}
{% block dash_active %}
  All tasks Near Due
{% endblock %}

{% block main_content %}
<a href="{% url "tasks:task_create" %}" class="btn btn-dark px-4 my-3">Create Task <i class="feather feather-plus"></i></a>

  <div class="card stretch stretch-full">
    <div class="card-body p-0">
      <div class="table-responsive">
        <div id="taskList_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
          <div class="row dt-row">
            <div class="col-sm-12">
              <table class="table table-hover dataTable no-footer" id="taskList" aria-describedby="taskList_info">
                <thead>
                  <tr>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">#</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">task Name</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Team Work</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Start Date</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">End Date</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Priority</th>
                    <th tabindex="0" aria-controls="taskList" rowspan="1" colspan="1">Status</th>
                    <th rowspan="1" colspan="2" class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for task in tasks %}
                    <tr class="single-item odd">
                      <td>{{ forloop.counter }}</td>
                      <td>{{ task.name|title }}</td>

                      <td>
                        <div class="d-flex">
                          {% for pro in task.team.member.all %}
                            <span class="avatar-image avatar-md me-1"><img src="{{ pro.profile.get_profile_image }}" alt="" class="img-fluid" /></span>
                          {% endfor %}
                        </div>
                      </td>

                      <td>{{ task.start_date }}</td>
                      <td>{{ task.due_date }}</td>
                      <td class="text-{{ task.get_priority_color }}" style="font-style: italic;">{{ task.priority }}</td>
                      <td class="text-{{ task.get_status_color }}" style="font-style: italic;">
                        <small>{{ task.status }}</small>
                        <div class="progress mt-2 ht-5">
                          <div class="progress-bar bg-{{task.get_progress_color}}"role="progressbar"
                            style="width: {{ task.progress }}%"></div>
                        </div>
                      </td>
                      <td>
                        <div class="hstack gap-2 justify-content-end">
                          {% if request.user == task.owner %}
                          <a href="{{ task.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          <a href="{% url "tasks:task_edit" task.pk %}" class="avatar-text avatar-md"><i class="feather feather-edit"></i></a>
                          <a href="{% url "tasks:task_delete" task.pk %}" class="avatar-text avatar-md"><i class="feather feather-trash-2"></i></a>
                          {% else %}
                          <a href="{{ task.get_absolute_url }}" class="avatar-text avatar-md"><i class="feather feather-eye"></i></a>
                          {% endif %}
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-5">
              <div class="dataTables_info" id="taskList_info" role="status" aria-live="polite">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} entries</div>
            </div>
            <div class="col-sm-12 col-md-7">
              <div class="dataTables_paginate paging_simple_numbers" id="taskList_paginate">
                <ul class="pagination ">
                  {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous mx-1" id="taskList_previous">
                      <a href="?page={{page_obj.previous_page_number}}" aria-controls="taskList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% else %}
                    <li class="paginate_button page-item previous disabled mx-1" id="taskList_previous">
                      <a href="#" aria-controls="taskList" data-dt-idx="previous" tabindex="0" class="page-link">Previous</a>
                    </li>
                  {% endif %}
                  <li class="paginate_button page-item active mx-1">
                    <a href="#" aria-controls="taskList" data-dt-idx="0" tabindex="0" class="page-link">{{ page_obj.number }}</a>
                  </li>
                  
                  <li class="paginate_button page-item mx-1">
                    <a class="page-link">{{ page_obj.paginator.num_pages }}</a>
                  </li>
                  {% if page_obj.has_next %}
                  <li class="paginate_button page-item next mx-1" id="taskList_next">
                    <a href="?page={{page_obj.next_page_number}}" aria-controls="taskList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                  </li>
                  {% else %}
                  <li class="paginate_button page-item next disabled mx-1" id="taskList_next">
                    <a href="#" aria-controls="taskList" data-dt-idx="next" tabindex="0" class="page-link">Next</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/update_task.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  Task/Update
{% endblock %}

{% block css %}

{% endblock %}

{% block dash_link %}
  Kanban</a>
{% endblock %}
{% block dash_active %}
  Task/{{task.name|title}} {{task.start_date}}
{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col bg-white p-5">
        <form action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-dark px-3 my-5" value="Update Task">

        </form>
    </div>
</div>
    
{% endblock %}